title: caroline needell
email: cneedell@mit.edu
description: >-
  PhD student 
url: "https://cneedell.github.io"   # must match Settings → Pages
baseurl: ""
lang: en
timezone: America/New_York

author:
  name: Caroline Needell
  email: cneedell@mit.edu

theme: minima
github_username: cneedell

header_pages:
  - research.md
  - photos.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

show_excerpts: false
sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - LICENSE
  - .jekyll-cache
